version: '3.3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    build: .
    command: python main.py run -h 0.0.0.0
    volumes:
      - ./:/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db

  script:
    build: .
    command:
      python google_sheets_proc.py
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  postgres_data:
